ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`localhost`) && PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    entryPoints: [ "web", "traefik" ]
ports:
  traefik:
    web:
      expose:
        default:true
      exposedPort: 80
      protocol: TCP
